export const RETIDO_ORDENACAO_AUTOR_LABELS: Record<string, string> = {
  CAT_AUDIO_VISUAL: 'Cat. Audio Visual',
  CDCAPEPI: 'Código Cap/Episódio',
  COD_AUDIO_VISUAL: 'Código Audio Visual',
  COD_FONOGRAMA: 'Código Fonograma',
  COD_OBRA: 'Código Obra',
  COD_POUT_POURRIT: 'Código Pout Pourrit',
  COMPETENCIA: 'Competência',
  EXECUCAO_SEGUNDOS: 'Execução/Segundos',
  IFPI: 'IFPI',
  INTERPRETE: 'Intérprete',
  NOME_SHOW: 'Nome Show',
  OCORRENCIA: 'Ocorrência',
  REF_AUTORAL: 'Ref.Autoral',
  RUBRICA: 'Rubrica',
  SITUACAO: 'Situação',
  TIT_AUDIO_VISUAL: 'Titulo Audio Visual',
  TIT_AUDIO_VISUAL_LOCAL: 'Titulo Audio Visual Local',
  TIT_CAPEPI: 'Titulo Cap/Episódio',
  TIT_CAPEPI_LOCAL: 'Titulo Cap/Episódio Local',
  TIT_OBRA: 'Titulo Obra',
  TIT_POUT_POURRIT: 'Titulo Pout Pourrit',
}

export const RETIDO_ORDENACAO_TITULAR_LABELS: Record<string, string> = {
  CAT_AUDIO_VISUAL: 'Cat. Audio Visual',
  CDCAPEPI: 'Código Cap/Episódio',
  CATEGORIA: 'Categoria',
  COD_AUDIO_VISUAL: 'Código Audio Visual',
  COD_FONOGRAMA: 'Código Fonograma',
  COD_OBRA: 'Código Obra',
  COD_POUT_POURRIT: 'Código Pout Pourrit',
  COD_TITULAR: 'Código Titular',
  COMPETENCIA: 'Competência',
  EXECUCAO_SEGUNDOS: 'Execução/Segundos',
  IFPI: 'IFPI',
  NOME_SHOW: 'Nome Show',
  NOME_TITULAR: 'Nome Titular',
  OCORRENCIA: 'Ocorrência',
  PSEUDO_TITULAR: 'Pseudo Titular',
  REF_AUTORAL: 'Ref.Autoral',
  REF_INTERPRETE: 'Intérprete',
  RUBRICA: 'Rubrica',
  SITUACAO: 'Situação',
  TIT_AUDIO_VISUAL: 'Titulo Audio Visual',
  TIT_AUDIO_VISUAL_LOCAL: 'Titulo Audio Visual Local',
  TIT_CAPEPI: 'Titulo Cap/Episódio',
  TIT_CAPEPI_LOCAL: 'Titulo Cap/Episódio Local',
  TIT_OBRA: 'Titulo Obra',
  TIT_POUT_POURRIT: 'Titulo Pout Pourrit',
}

export const RETIDO_ORDENACAO_CONEXO_LABELS: Record<string, string> = {
  CAT_AUDIO_VISUAL: 'Cat. Audio Visual',
  CDCAPEPI: 'Código Cap/Episódio',
  COD_AUDIO_VISUAL: 'Código Audio Visual',
  COD_FONOGRAMA: 'Código Fonograma',
  COD_OBRA: 'Código Obra',
  COD_POUT_POURRIT: 'Código Pout Pourrit',
  COMPETENCIA: 'Competência',
  EXECUCAO_SEGUNDOS: 'Execução/Segundos',
  GRAVADORA: 'Gravadora',
  IFPI: 'IFPI',
  INTERPRETE: 'Intérprete',
  OCORRENCIA: 'Ocorrência',
  REF_AUTORAL: 'Ref.Autoral',
  RUBRICA: 'Rubrica',
  SITUACAO: 'Situação',
  TIT_AUDIO_VISUAL: 'Titulo Audio Visual',
  TIT_AUDIO_VISUAL_LOCAL: 'Titulo Audio Visual Local',
  TIT_CAPEPI: 'Titulo Cap/Episódio',
  TIT_CAPEPI_LOCAL: 'Titulo Cap/Episódio Local',
  TIT_OBRA: 'Titulo Obra',
  TIT_POUT_POURRIT: 'Titulo Pout Pourrit',
}

export const PESQUISA_RETIDO_LABELS: Record<string, string> = {
  COMECANDO: 'Começando com...',
  CONTENDO: '...Que contenha...',
  EXATAMENTE: 'Exatamente',
  TERMINANDO: '...Terminando com',
}

export const CONCATENACAO_LABELS: Record<string, string> = {
  OU: 'ou',
  E: 'e',
}

export const SELECAO_DIGITAL_LABELS: Record<string, string> = {
  TODOS: 'Todos',
  EXCETO_DIGITAL: 'Todos exceto Digital',
  SOMENTE_DIGITAL: 'Somente Digital',
}

export const RETIDO_UI_LABELS = {
  tabs: {
    autoral: 'Autoral',
    conexo: 'Conexo',
    titular: 'Titular',
    ariaModoPesquisa: 'Modo de pesquisa de retido',
  },
  loading: 'Carregando resultados...',
  emptyHint: 'Preencha o primeiro critério de pesquisa e clique em Pesquisar.',
  scrollHint: 'Deslize horizontalmente para ver todas as colunas.',
  selectAll: 'Selecionar todos desta página',
  selectRow: 'Selecionar linha',
  viewDetail: 'Ver detalhes',
  fields: {
    ordenacao1: 'Campo de pesquisa (1)',
    ordenacao2: 'Campo de pesquisa (2)',
    pesquisa1: 'Tipo de pesquisa (1)',
    pesquisa2: 'Tipo de pesquisa (2)',
    texto1: 'Pesquisa',
    texto2: 'Texto (2)',
    concatenacao: 'Concatenar com',
    selecaoDigital: 'Digital',
  },
  placeholders: {
    ordenacao: 'Selecione',
    pesquisa: 'Selecione',
    semSegundoCriterio: 'Sem segundo critério',
  },
  actions: {
    search: 'Pesquisar',
    clear: 'Limpar',
  },
  columns: {
    pkCodigo: 'Código',
    compet: 'Competência',
    rubrica: 'Rubrica',
    nmObra: 'Título obra',
    nmTitular: 'Nome titular',
    cdTitular: 'Código titular',
    categoria: 'Categoria',
    refAutoral: 'Ref. autoral',
    refInterprete: 'Intérprete',
    refGravadora: 'Gravadora',
    dscPlano: 'Plano digital',
    situacao: 'Situação',
    actions: 'Ações',
    nroOcor: 'Ocorrências',
    motivoRetencao: 'Motivo retenção',
  },
  toolbar: {
    selected: (count: number) => `Selecionados: ${count}`,
    excel: 'Gerar Excel',
    excelTodos: 'Excel (todos os resultados)',
    excelTodosSuccess: 'Planilha gerada com sucesso.',
    clearSelection: 'Limpar seleção',
  },
  excelModal: {
    title: 'Exportar Excel',
    description: (count: number) =>
      `Serão exportados ${count} registro(s) selecionado(s). Deseja continuar?`,
    cancel: 'Cancelar',
    confirm: 'Gerar e baixar',
    generating: 'Gerando...',
  },
  detailModal: {
    title: 'Detalhe do retido',
    tableField: 'Campo',
    tableValue: 'Valor',
    nmAudio: 'Áudio visual',
    nroOcor: 'Ocorrências',
    perDe: 'Período de',
    perAte: 'Período até',
    motivoRetencao: 'Motivo retenção',
  },
} as const
